sudo: required

services:
  - docker

before_install:
  - docker build -t wagnerdeandrade/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run -e CI=true wagnerdeandrade/react-test npm test

after_sucess:
  - docker build -t wagnerdeandrade/multi-client ./client
  - docker build -t wagnerdeandrade/multi-nginx ./nginx
  - docker build -t wagnerdeandrade/multi-server ./server
  - docker build -t wagnerdeandrade/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # take those and push to docker hub
  - docker push wagnerrogeriodeandrade/multi-client
  - docker push wagnerrogeriodeandrade/multi-nginx
  - docker push wagnerrogeriodeandrade/multi-server
  - docker push wagnerrogeriodeandrade/multi-worker


